name: Minecraft Discord Bot
version: "0.1.6"
slug: minecraft_discord_bot
description: "A Discord bot to manage your Minecraft server"
arch:
  - aarch64
startup: services
boot: auto
options:
  BOT_TOKEN: ""
  DEBIAN_MAC: ""
  RCON_PASSWORD: ""
  CHANNEL_ID: ""
schema:
  BOT_TOKEN: password
  DEBIAN_MAC: password
  RCON_PASSWORD: password
  CHANNEL_ID: password
