name: Minecraft Discord Bot
version: "0.1.1"
slug: minecraft_discord_bot
description: "A Discord bot to manage your Minecraft server"
startup: services
boot: auto
options:
  BOT_TOKEN: ""
  DEBIAN_MAC: ""
  RCON_PASSWORD: ""
  CHANNEL_ID: ""
schema:
  BOT_TOKEN: str
  DEBIAN_MAC: str
  RCON_PASSWORD: str
  CHANNEL_ID: str
